name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
  
    - name: Short SHA
      run: |
        echo "SHORT_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
    
    - name: Docker Build
      run: |
          docker buildx build . \
          --file Dockerfile \
          --tag ghcr.io/${{ github.repository_owner }}/idk8s-apiv2:latest \
          --tag ghcr.io/${{ github.repository_owner }}/idk8s-apiv2:${{ env.SHORT_SHA }} \
          --build-arg IMAGE_TAG=${{ env.SHORT_SHA }}

    - name: Push to GitHub Container Registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
        docker push ghcr.io/${{ github.repository_owner }}/idk8s-apiv2:${{ env.SHORT_SHA }}
        # ghcr.io/${{ github.repository_owner }}/idk8s-apiv2:latest
